function getModuleInfo() {
  return {
    name: 'Convert all PDFs to image',
    description: '<html><h1>PDF to Image Converter</h1><h2><img src="icon,warning,16"><img src="icon,warning,16"> Warnings and Alerts <img src="icon,warning,16"><img src="icon,warning,16"></h2><p><img src="icon,desktop_windows,16">Module exclusively for use on the Windows operating system<img src="icon,window,16"></p><p>This module uses external programs to perform file conversion. Use it at your own risk.</p><hr><h2>Requirements to Run the Module</h2><p>Down\u006Coad <a href="https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=win-x64&os=win10&apphost_version=8.0.10">.NET 8</a> and install it.</p><p>Down\u006Coad the executable<a href="https://github.com/SrTonn/PDF2Image/releases"> PDF2Image</a>(v1.1.0+).</p><hr><h2>Necessary Configurations</h2><ol><li>Save the PDF2Image file in the folder C:\\Holyrics\\Holyrics\\files\\media\\file\\PDF2Image</li><li>Open the module settings and click the "Open Permission Settings" button, then select the PDF2Image file using the add button</li></ol><p>The path will look similar or identical to this: PDF2Image/PDF2Image.exe</p><p>Note: Open the Holyrics file folder through the interface, go to the main screen, and look for the file tab. Click the folder icon, create a folder inside, and paste the executable there.</p><p>Note 2: The exe file can be saved in any subfolder starting from the file location. If you choose to save the file in a different folder from the one suggested in this tutorial, you must provide the correct path in the module settings.</p><h4>Your PDF converter is ready to use!</h4></html>',
    i18n: {
      name: {
        pt: 'Converter todos os PDFs para imagem',
      },
      description: {
        pt: '<html><h1>Conversor de PDF para imagens</h1><h2><img src="icon,warning,16"><img src="icon,warning,16"> Avisos e alertas <img src="icon,warning,16"><img src="icon,warning,16"></h2><p><img src="icon,desktop_windows,16">Módulo exclusivo para utilização no sistema operacional windows<img src="icon,window,16"></p><p>Este módulo utiliza de programas externos para fazer a conversão de arquivo, utilize por sua conta e risco</p><hr><h2>Requisitos para executar o módulo</h2><p>Baixe o <a href="https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=win-x64&os=win10&apphost_version=8.0.10">.NET 8</a> e instale.</p><p>Baixe o executavel <a href="https://github.com/SrTonn/PDF2Image/releases">PDF2Image</a>(v1.1.0+).</p><hr><h2>Configurações necessárias</h2><ol><li>Salve o arquivo PDF2Image na pasta C:\\Holyrics\\Holyrics\\files\\media\\file\\PDF2Image</li><li>Abra as configurações do módulo e clique no botão "Abrir configurações de permissões", em seguida selecione o arquivo PDF2Image através do botão adicionar</li><p>O caminho será parecido ou igual a este: PDF2Image/PDF2Image.exe</p></ol><p>OBS: Abra a pasta arquivo do holyrics através da interface, vá até a tela principal e procure pela aba arquivo, clique no icone de pasta, crie uma pasta lá dentro e cole o executavel</p><p>OBS²: O arquivo exe pode ser salvo em qualquer subpasta a partir do local arquivo, caso opte por guardar o arquivo em uma pasta diferente da sugerida nesse tutorial é necessário informar o caminho correto nas configurações do módulo.</p><h4>Seu conversor de PDF está pronto para uso !</h4></html>',
      }
    }
  }
}